name: Check .proto files

on:
  workflow_call:
  workflow_dispatch:

env:
  POETRY_VERSION: 1.2.2
  PYTHON_VERSION: 3.9

jobs:
  check_protos:
    name: Check .proto files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .github/check_protos/.venv
          key: check-protos-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.github/check_protos/poetry.lock') }}
      - name: Install dependencies
        run: poetry install -v
        working-directory: ./.github/check_protos
      - name: Check .proto files
        run: poetry run python _check_protos.py
        working-directory: ./.github/check_protos