name: CI

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  check_protos:
    name: Check .proto files
    uses: ./.github/workflows/check_protos.yml
  create_ci_artifacts:
    name: Create CI artifacts
    uses: ./.github/workflows/create_ci_artifacts.yml
    