name: Build Release artifacts

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_release_artifacts:
    name: Download and Build artifacts
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/download-artifact@v3
      id: download_artifacts
      with:
        path: ${{ runner.temp }}\measurementlink-labview-artifacts